name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "**/*.swift"
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer

jobs:
  build-test:
    name: Build and Test
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build --build-tests -Xswiftc -warnings-as-errors

      - name: Test
        run: swift test --skip-build
      
      - name: Build for Release
        run: swift build -c release -Xswiftc -warnings-as-errors
  
  build-and-test-platforms:
    name: Build and Test (${{ matrix.name }})
    runs-on: macos-15
    continue-on-error: true
    strategy:
      matrix:
        include:
          - name: iOS
            destination: platform=iOS Simulator,name=iPhone 16,OS=18.2
          - name: watchOS
            destination: platform=watchOS Simulator,name=Apple Watch Series 10 (46mm),OS=11.2
          - name: tvOS
            destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=18.2
          - name: visionOS
            destination: platform=visionOS Simulator,name=Apple Vision Pro,OS=2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: set -o pipefail && NSUnbufferedIO=YES xcodebuild build-for-testing -scheme SwiftRedux -destination '${{ matrix.destination }}'
      
      - name: Test
        run: set -o pipefail && NSUnbufferedIO=YES xcodebuild test-without-building -scheme SwiftRedux -destination '${{ matrix.destination }}'
